repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.5.0
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: |
          (?x)^(
              .*ro-crate-metadata.json$|
              modules/nf-core/.*|
              subworkflows/nf-core/.*|
              .*\.snap$
          )$
      - id: end-of-file-fixer
        exclude: |
          (?x)^(
              .*ro-crate-metadata.json$|
              modules/nf-core/.*|
              subworkflows/nf-core/.*|
              .*\.snap$
          )$
  - repo: local
    hooks:
      - id: version_checks
        name: Version checks
        language: system
        entry: >
          .github/version_checks.sh
        always_run: true
        fail_fast: true
        pass_filenames: false
