repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.6.2
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: |
          (?x)^(
              .*ro-crate-metadata.json$|
              modules/nf-core/.*|
              modules/gallvp/.*|
              subworkflows/nf-core/.*|
              subworkflows/gallvp/.*|
              .*\.snap$
          )$
      - id: end-of-file-fixer
        exclude: |
          (?x)^(
              .*ro-crate-metadata.json$|
              modules/nf-core/.*|
              modules/gallvp/.*|
              subworkflows/nf-core/.*|
              subworkflows/gallvp/.*|
              .*\.snap$
          )$
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.17.1"
    hooks:
      - id: mypy
        files: bin/.*\.py
        additional_dependencies:
          - types-tabulate
          - types-PyYAML
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
      - id: ruff
        files: bin/.*\.py
        args:
          [
            --fix,
            --exit-non-zero-on-fix,
            --config,
            "lint.select=['I','E','F','UP','N','Q','RET','SLF','C4','YTT','T10','RSE','TID','INT','ARG','FLY','PERF','FURB','RUF','W']",
            --config,
            "line-length=160",
            --config,
            "target-version='py311'",
          ]
      - id: ruff-format
        files: bin/.*\.py
  - repo: local
    hooks:
      - id: version_checks
        name: Version checks
        language: system
        entry: >
          .github/version_checks.sh
        always_run: true
        fail_fast: true
        pass_filenames: false
